#addons:
#  apt:
#    packages:
#      - python-pygments
#
#install:
#  - rm -rf public || exit 0

arch:
  - arm64

script:
  - cd src
  #- uname -a
  #- cat /proc/cpuinfo
  #- cat /etc/issue
  #- free -m
  #- docker info
  #- docker images
  #- ip addr
  #- ping -c1 www.google.com
  #- sudo add-apt-repository ppa:ansible/ansible -y && sudo apt-get update -y && sudo apt-get install -y ansible git python-pip && ansible --version
  - sudo apt-get install -y git python-pip python3-virtualenv python3-pip python3-venv
  - sudo su
  - whoami && pwd 
  - python3 -m pip install --user --upgrade pip && python3 -m pip install --user virtualenv
  - pwd
  - git clone https://github.com/kubernetes-sigs/kubespray.git
  - cd kubespray && git checkout tags/v2.13.1 -b kubespray2131 
  - python3 -m venv env && python3 -m venv env && source env/bin/activate 
  - pip3 install -r requirements.txt
  - wget https://gist.githubusercontent.com/purplepalmdash/5903832d353efd67d4a13ed01f878988/raw/cf02202d2e3079e11873f1926ea83238e72159ec/dinddiffs.diff
  #- cat dinddiffs.diff | patch -p1
  - cd contrib/dind &&  pip3 install -r requirements.txt
  - ansible --version
  - pip3 install --upgrade pip3
  - pip3 install docker; pip3 install docker-py
  - ansible-playbook -i hosts dind-cluster.yaml
  - whoami && pwd  && pip list | egrep 'docker|docker-py|requests'
  - sudo docker ps


#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: src/public
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  on:
#    branch: master
#  repo: purplepalmdash/purplepalmdash.github.io
#  target_branch: master

