#addons:
#  apt:
#    packages:
#      - python-pygments
#
#install:
#  - rm -rf public || exit 0

arch:
  - arm64

script:
  - cd src
  #- uname -a
  #- cat /proc/cpuinfo
  #- cat /etc/issue
  #- free -m
  #- docker info
  #- docker images
  #- ip addr
  #- ping -c1 www.google.com
  - sudo add-apt-repository ppa:ansible/ansible -y && sudo apt-get update -y && sudo apt-get install -y ansible git python-pip && ansible --version
  - pwd
  - git clone https://github.com/kubernetes-sigs/kubespray.git
  - cd kubespray && git checkout tags/v2.13.1 -b kubespray2131 && sudo pip install -r requirements.txt &&  pip install -r requirements.txt
  - wget https://gist.githubusercontent.com/purplepalmdash/5903832d353efd67d4a13ed01f878988/raw/cf02202d2e3079e11873f1926ea83238e72159ec/dinddiffs.diff
  - cat dinddiffs.diff | patch -p1
  - cd contrib/dind && sudo pip install -r requirements.txt &&  pip install -r requirements.txt
  - sudo pip install docker; sudo pip install docker-py; pip install docker; pip install docker-py
  - sudo pip uninstall -y docker docker-py requests; sudo pip install docker; sudo pip install docker-py; sudo pip install requests>=2.20.1
  - pip uninstall -y docker docker-py requests;  pip install docker;  pip install docker-py;  pip install requests>=2.20.1
  - sudo pip install -U requests; pip install -U requests
  - sudo ansible-playbook -i hosts dind-cluster.yaml
  - sudo docker ps


#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: src/public
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  on:
#    branch: master
#  repo: purplepalmdash/purplepalmdash.github.io
#  target_branch: master

