#addons:
#  apt:
#    packages:
#      - python-pygments
#
#install:
#  - rm -rf public || exit 0

arch:
  - arm64

script:
  - cd src
  #- uname -a
  #- cat /proc/cpuinfo
  #- cat /etc/issue
  #- free -m
  #- docker info
  #- docker images
  #- ip addr
  #- ping -c1 www.google.com
  #- sudo add-apt-repository ppa:ansible/ansible -y && sudo apt-get update -y && sudo apt-get install -y ansible git python-pip && ansible --version
  - ps -ef | grep sshd
  - sudo apt-get install -y git python-pip python3-virtualenv python3-pip python3-venv python-docker python3-docker openssh-server
  - mkdir -p /var/run/sshd && /usr/sbin/sshd -D & 
  #- sudo mkdir -p /tmp/releases && sudo chmod 777 -R /tmp/releases && sudo chown -R travis /tmp/releases
  #- mkdir cached && chmod 777 -R cached
  #- mkdir cached1 && chmod 777 -R cached1
  - ps -ef | grep sshd
  - whoami && pwd 
  - python3 -m pip install --user --upgrade pip && python3 -m pip install --user virtualenv
  - git clone https://github.com/kubernetes-sigs/kubespray.git
  - cd kubespray && git checkout tags/v2.13.1 -b kubespray2131 
  - sed -i '14,21 s/^/#/' ./roles/download/tasks/download_file.yml
  - wget http://209.141.35.192/patched/dinddiffarm64.diff
  - wget http://209.141.35.192/patched/cluster1.yml
  - wget http://209.141.35.192/patched/rong-vars.yml
  - wget http://209.141.35.192/patched/hosts.ini
  - cp hosts.ini inventory/sample/hosts.ini
  - ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa 2>/dev/null <<< y >/dev/null
  - cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
  - cat dinddiffarm64.diff | patch -p1
  - python3 -m venv env && python3 -m venv env && source env/bin/activate 
  - pip3  install --upgrade setuptools
  - pip3 install  --no-cache-dir -r requirements.txt
  - cd contrib/dind &&  pip3 install -r requirements.txt
  - ansible --version
  - pip3 install --upgrade pip3
  - pip3 install docker; pip3 install docker-py
  - pip install docker; pip install docker-py
  - ansible-playbook --version
  - cd ../../
  - pwd && ls
  - ansible-playbook -i inventory/sample/hosts.ini cluster1.yml --extra-vars @rong-vars.yml
  #- sudo mkdir -p /home/vsts/docker && sudo chmod 777 -R /home/vsts/docker
  #- sudo mkdir -p /home/vsts/releases && sudo chmod 777 -R /home/vsts/releases
  #- ansible-playbook -i hosts dind-cluster.yaml
  #- whoami && pwd  && pip list | egrep 'docker|docker-py|requests'
  #- sudo docker ps


#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: src/public
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  on:
#    branch: master
#  repo: purplepalmdash/purplepalmdash.github.io
#  target_branch: master

